export const actionTypes = {
    FETCH_MATCH_REQUEST:"FETCH_MATCH_REQUEST",
    FETCH_MATCH_SUCCESS:"FETCH_MATCH_SUCCESS",
    FETCH_MATCH_FAILURE:"FETCH_MATCH_FAILURE",
    ADD_TO_LIKED_MATCHES: "ADD_TO_LIKED_MATCHES",
    REMOVE_LIKED_MATCH: "REMOVE_LIKED_MATCHE",
    SET_SEARCH_QUERY: "REMOVE_LIKED_MATCH"
}